name: 'Find Issues by Field'
description: 'Find Projects (Beta) issue that have a field with a certain value'
inputs:
  token:
    description: 'Personal access token with auth for the intended project'
    required: true
  organization:
    description: 'Organization slug that the environments project resides in'
    required: true
  projectNumber:
    description: 'Numerical id of the environments project'
    required: true
  fieldName:
    description: 'Name of the field to filter issues by'
    required: true
  fieldValue:
    description: 'Value of the field to filter issues by'
    required: true

outputs:
  issues:
    description: 'List of issues that have a matching field with title and a field map'


runs:
  using: 'node16'
  main: 'dist/index.js'
