name: 'Launch Darkly feature flags sync'
description: 'Sync Launch Darkly feature flags between environments'
inputs:
  projectKey:
    description: 'Project key'
    required: true
  sourceEnv:
    description: 'Source environment key'
    required: true
  destinationEnv:
    description: 'Destination environment key'
    required: true
  apiToken:
    description: 'LaunchDarkly personal access token with write-level access'
    required: true
  flag:
    description: 'Sync only the specified flag'
    required: false
  tag:
    description: 'Sync flags with the given tag(s). Only flags with all tags will sync.'
    required: false
  omitSegments:
    description: 'Omit segments when syncing'
    required: false
    default: 'false'
  host:
    description: 'Hostname override'
    required: false
    default: 'https://app.launchdarkly.com'
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'
  dryRun:
    description: 'Preview changes'
    required: false
    default: 'false'
  debug:
    description: 'Enable HTTP debugging'
    required: false
    default: 'false'

runs:
  using: 'node16'
  main: 'dist/index.js'
