name: 'Markdown Jira Release Notes'
description: 'Generate markdown release notes from a list of Jira issues'
inputs:
  title:
    description: 'Title for the release notes, i.e. React v1.2.3'
    required: false
  changelogFile:
    description: 'JSON file path with issues and other commits'
    required: false
    default: 'temp/changelog.json'

outputs:
  releaseNotes:
    description: 'Markdown formatted release notes'

runs:
  using: 'node20'
  main: 'dist/index.js'
