version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/api-docs-compliance"
      - "/aws-environment-param-sync"
      - "/build-java"
      - "/cleanup-java"
      - "/deploy-java"
      - "/github-branch-dispatch"
      - "/github-delete-draft-releases"
      - "/github-download-multi-run-artifacts"
      - "/github-global-autolink"
      - "/github-release-find-by-name"
      - "/github-trigger-workflows-and-wait"
      - "/jira-deployment-status"
      - "/jira-environment-revision-search"
      - "/jira-environment-revision-set"
      - "/jira-environment-ticket-create"
      - "/jira-environment-ticket-delete"
      - "/jira-issues-from-commits"
      - "/jira-issues-update-fix-version"
      - "/jira-project-version-create"
      - "/jira-project-version-update"
      - "/jira-release-notes-markdown"
      - "/jira-release-notes-slack"
      - "/launchdarkly-flags-sync"
      - "/launchdarkly-segments-sync"
      - "/open-vpn-connect"
      - "/slack-deployment-status"
      - "/sync-image-between-ecrs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"

  - package-ecosystem: "npm"
    directories:
      - "/aws-environment-param-sync"
      - "/github-branch-dispatch"
      - "/github-delete-draft-releases"
      - "/github-download-multi-run-artifacts"
      - "/github-global-autolink"
      - "/github-release-find-by-name"
      - "/github-trigger-workflows-and-wait"
      - "/jira-environment-revision-search"
      - "/jira-environment-revision-set"
      - "/jira-environment-ticket-create"
      - "/jira-environment-ticket-delete"
      - "/jira-issues-from-commits"
      - "/jira-issues-update-fix-version"
      - "/jira-project-version-create"
      - "/jira-project-version-update"
      - "/jira-release-notes-markdown"
      - "/jira-release-notes-slack"
      - "/launchdarkly-flags-sync"
      - "/launchdarkly-segments-sync"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 6
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"
