version: 2
updates:

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/build-java"
      - "/deploy-java"
      - "/deployment-status"
      - "/jira-deployment-status"
      - "/open-vpn-connect"
      - "/slack-deployment-status"
      - "/sync-image-between-ecrs"
    schedule:
      interval: "weekly"
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"
