version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"

  - package-ecosystem: "github-actions"
    directory: "/deployment-status"
    schedule:
      interval: "weekly"
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"

  - package-ecosystem: "github-actions"
    directory: "/jira-deployment-status"
    schedule:
      interval: "weekly"
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"

  - package-ecosystem: "github-actions"
    directory: "/slack-deployment-status"
    schedule:
      interval: "weekly"
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"
