version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1 # Limit PR's to 1 to avoid overwhelming
    schedule:
      interval: "weekly"
    assignees:
      - "@cartoncloud/code-owners-platform"
    reviewers:
      - "@cartoncloud/code-owners-platform"
