name: 'Create Jira Project Version'
description: 'Creates a new Jira release'
inputs:
  username:
    description: 'Jira username to use to call the API'
    required: true
  password:
    description: 'Jira password to use to call the API'
    required: true
  serverAddress:
    description: 'Jira server address i.e. acme.atlassian.net'
    required: true
  projectId:
    description: 'The id of the Jira project to create the release in'
    required: true
  name:
    description: 'The name to give the release'
    required: true
  description:
    description: 'Optional description for the release'
    required: false
  isReleased:
    description: 'Whether to mark the created release as unreleased or released'
    required: true
  timezone:
    description: 'Timezone for the release date'
    required: false
    default: 'Australia/Brisbane'

outputs:
  releaseId:
    description: 'Id of the created Jira release'

runs:
  using: 'node20'
  main: 'dist/index.js'
