name: 'Update Project Issue Field'
description: 'Update a field on a Projects (Beta) issue'
inputs:
  token:
    description: 'Token with auth to edit the given project'
    required: true
  organization:
    description: 'Organization slug'
    required: true
  projectNumber:
    description: 'Project number, i.e. 2'
    required: true
  issue:
    description: 'Name of the issue to update'
    required: true
  field:
    description: 'Name of the field to update'
    required: true
  value:
    description: 'New field value'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
