name: 'AWS Environment Param Sync'
description: 'Syncs AWS params to environments and environment variables within repository.'
inputs:
  environmentPath:
    description: 'Path to the environment params containing environment names.'
    required: false
    default: '/terraform/cartoncloud-app/environments'
  environmentVariablesPath:
    description: 'Base path to environment variables. For each environment, <<environmentVariablePath>>/<<environment>> is used.'
    required: false
    default: '/terraform/cartoncloud-app'

runs:
  using: 'node16'
  main: 'dist/index.js'
