name: 'Jira Assign Ticket To User'
description: 'Takes the ticket key and assigns it to a given user'
inputs:
  jiraServer:
    description: 'Jira server address i.e. acme.atlassian.net'
    required: true
  jiraUsername:
    description: 'Jira username to use to call the API'
    required: true
  jiraPassword:
    description: 'Jira password to use to call the API'
    required: true
  jiraAssignedUser: 
    description: 'Jira id of the developer to assign the ticket to'
    required: true
  jiraIssueKey:
    description: 'Jira issue key of the ticket to be assigned'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
