name: 'Slack JIRA Release Notes'
description: 'Generates Slack formatted JIRA release notes from commit messages and updates each issues JIRA fix version'
inputs:
  jiraServer:
    description: 'JIRA server address i.e. support.cartoncloud.com'
    required: true
  jiraUsername:
    description: 'JIRA username to use to call the API'
    required: true
  jiraPassword:
    description: 'JIRA password to use to call the API'
    required: true
  jiraProjectKey:
    description: 'The key/prefix of the JIRA project. i.e. CC'
    required: true
  jiraReleaseId:
    description: 'JIRA release id to add issues to'
    required: false

  slackToken:
    description: 'Slack Bot Token to use to find Slack users by email'
    required: true

  appName:
    description: 'Name of the application. i.e. React'
    required: true
  revision:
    description: 'Release version/tag to compare commits up to'
    required: true
  refFrom:
    description: 'Tag or commit ref to compare commits from'
    required: true

outputs:
  releaseNotes:
    description: 'Slack formatted JSON release notes'

runs:
  using: 'node16'
  main: 'dist/index.js'
