name: Build

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - branch-dispatch
          - create-jira-release
          - find-issues-by-field
          - slack-jira-release-notes
          - update-jira-release
          - update-project-issue

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ${{ matrix.package }}/package-lock.json

      - name: Install depdendencies
        working-directory: ${{ matrix.package }}
        run: npm ci

      - name: Compile to single JS file
        working-directory: ${{ matrix.package }}
        run: npm run build

      - name: Prepare upload
        run: |
          mkdir -p upload/${{ matrix.package }}/dist
          cp -a ${{ matrix.package }}/dist/. upload/${{ matrix.package }}/dist/

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-packages
          path: upload
          retention-days: 1

  debug:
    name: Debug
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: compiled-packages

      - name: Display structure of downloaded files
        run: ls -R
