name: Workflow Test/Build

on:
  workflow_call:
    inputs:
      pomVersion:
        type: string
        required: false
        default: ${{ github.sha }}
    secrets:
      awsKeyId:
        required: true
      awsSecretKey:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.awsKeyId }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.awsSecretKey }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Update pom version
        run: mvn versions:set -DnewVersion="${{ inputs.pomVersion }}"

      - name: Build project
        run: mvn -Dmaven.wagon.http.pool=false -s settings.xml -B clean deploy

