name: Create Jira Project Version Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Jira Release
        uses: ./jira-create-project-version
        with:
          username: ${{ secrets.JIRA_USERNAME }}
          password: ${{ secrets.JIRA_PASSWORD }}
          serverAddress: cartoncloud.atlassian.net
          projectId: 10002
          name: Sample Release
          description: 'Created by actions/jira-create-project-version'
          isReleased: false
