name: Build Actions

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          - github-branch-dispatch
          - github-delete-draft-releases
          - github-global-autolink
          - github-release-find-by-name
          - jira-environment-revision-search
          - jira-environment-revision-set
          - jira-issues-from-commits
          - jira-issues-update-fix-version
          - jira-project-version-create
          - jira-project-version-update
          - jira-release-notes-markdown
          - jira-release-notes-slack

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: ${{ matrix.package }}/package-lock.json

      - name: Install depdendencies
        working-directory: ${{ matrix.package }}
        run: npm ci

      - name: Compile to single JS file
        working-directory: ${{ matrix.package }}
        run: npm run build

      - name: Prepare upload
        run: |
          mkdir -p upload/${{ matrix.package }}/dist
          cp -a ${{ matrix.package }}/dist/. upload/${{ matrix.package }}/dist/

      - uses: actions/upload-artifact@v3
        with:
          name: compiled-packages
          path: upload
          retention-days: 1

  commit:
    name: Commit Changes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Remove existing compiled actions
        run: find . -type d -name dist -prune -exec rm -rf {} \;

      - uses: actions/download-artifact@v3
        with:
          name: compiled-packages

      - name: Changed files
        run: git diff --name-only

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        continue-on-error: true
        with:
          commit_message: Compile actions
