name: Force New Deployment

on:
  workflow_call:
    inputs:
      environmentName:
        type: string
        required: true
      serviceName:
        type: string
        required: true

jobs:
  force-new-deployment:
    name: Forcing new deployment
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency: deploy-${{ inputs.environmentName }}
    environment:
      name: ${{ github.event.inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Forcing new deployment for ${{ vars.CLUSTER_NAME }} - ${{ inputs.serviceName }}
        run: |
          aws ecs update-service --cluster ${{ vars.CLUSTER_NAME }} --service ${{ inputs.serviceName }} --force-new-deployment
