name: Release Labels for Java

on:
  workflow_call:
    inputs:
      appName:
        type: string
        required: true
      pullRequestNumber: # TODO: Remove
        type: string
        required: false
      containsReleaseLabel: # TODO: Remove
        type: boolean
        required: false
      prHeadRef: # TODO: Remove
        type: string
        required: false
      githubEventAction: # TODO: Remove
        type: string
        required: false

jobs:
  labels:
    name: Required Labels
    runs-on: ubuntu-latest
    steps:
      - name: Add release label
        run: gh pr edit $PR --repo $REPO --add-label "Release"
        if: ${{ github.event.action == 'opened' && contains(github.event.pull_request.labels.*.name, 'Release') == false }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: '${{ github.repository_owner }}/${{ inputs.appName }}'
          PR: ${{ github.event.pull_request.number }}

      - name: Check for test pass labels
        uses: mheap/github-action-required-labels@v3
        if: ${{ github.event.pull_request.head.ref == 'release/production' }}
        with:
          mode: exactly
          count: 2
          labels: "API Functional Pass, End-to-end Pass"

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: labels
    if: github.event.action == 'labeled' && github.event.pull_request.head.ref == 'release/production' && (github.event.label.name == 'API Functional Pass' || github.event.label.name == 'End-to-end Pass')
    concurrency: deploy-staging01

    environment:
      name: staging01
      url: http://app.staging01/

    env:
      environmentName: staging01
      environmentTag: staging01
      environmentUrl: http://app.staging01/

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          path: repo

      - name: Get draft release
        id: draft-release
        uses: cartoncloud/actions/github-release-find-by-name@v3
        with:
          name: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Deploy
        uses: cartoncloud/actions/deploy-java@v3
        with:
          appName: ${{ inputs.appName }}
          revision: ${{ fromJson(steps.draft-release.outputs.release).tag_name }}
          revisionUrl: ${{ fromJson(steps.draft-release.outputs.release).html_url }}
          environment: ${{ env.environmentName }}
          environmentUrl: ${{ env.environmentUrl }}
          environmentTag: ${{ env.environmentTag }}
          existingImageTag: ${{ github.event.pull_request.head.sha  }}
          awsRegion: ${{ vars.AWS_REGION }}
          slackBotToken: ${{ secrets.SLACK_BOT_TOKEN }}
          jiraServer: ${{ vars.JIRA_SERVER }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
          gitHubPAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
