name: Java Branch Push

on:
  workflow_call:
    inputs:
      appName:
        type: string
        required: true
      githubRefName:
        type: string
        required: false
      jasperBuild:
        type: boolean
        required: false

jobs:
  build:
    if: ${{ inputs.postgres == false }}
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        # Docker Hub image
        image: redis
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.23
        env:
          discovery.type: single-node
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          # Maps port 9200 on service container to the host
          - 9200:9200

    steps:
      - name: Add hosts to /etc/hosts
        run: sudo echo "127.0.0.1 postgres.localhost.com" | sudo tee -a /etc/hosts

      - name: Build
        uses: cartoncloud/actions/build-java@v3
        with:
          appName: ${{ inputs.appName }}
          mavenS3AccessKeyId: ${{ secrets.TEMP_MAVEN_S3_ACCESS_KEY_ID }}
          mavenS3SecretAccessKey: ${{ secrets.TEMP_MAVEN_S3_SECRET_ACCESS_KEY }}
          sonarUrl: ${{ vars.SONAR_HOST_URL }}
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          jasperBuild: ${{ inputs.jasperBuild }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          javaVersion: ${{ inputs.javaVersion }}

  auto-update-list:
    name: Environment Updates
    runs-on: ubuntu-latest
    needs: build

    outputs:
      environments: ${{ steps.find-issues.outputs.environments }}

    steps:
      - uses: cartoncloud/actions/jira-environment-revision-search@v3
        id: find-issues
        with:
          jiraServer: ${{ vars.JIRA_SERVER }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
          projectKey: ${{ vars.JIRA_ENVIRONMENT_PROJECT_KEY }}
          appName: ${{ inputs.appName }}
          revision: ${{ github.ref_name }}
          nameField: ${{ vars.JIRA_ENVIRONMENT_KEY_FIELD }}
          urlField: ${{ vars.JIRA_ENVIRONMENT_URL_FIELD }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build, auto-update-list]
    if: needs.auto-update-list.outputs.environments != '[]'

    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJSON(needs.auto-update-list.outputs.environments) }}

    concurrency: deploy-${{ matrix.environment.name }}
    environment:
      name: ${{ matrix.environment.name }}
      url: ${{ matrix.environment.url }}

    steps:
      - name: Deploy
        uses: cartoncloud/actions/deploy-java@v3
        with:
          appName: ${{ inputs.appName }}
          revision: ${{ github.ref_name }}
          revisionUrl: ${{ github.event.repository.html_url }}/tree/${{ github.ref_name }}
          environment: ${{ matrix.environment.name }}
          environmentUrl: ${{ matrix.environment.url }}
          environmentTag: ${{ vars.DOCKER_ENVIRONMENT_TAG }}
          existingImageTag: ${{ github.sha }}
          awsRegion: ${{ vars.AWS_REGION }}
          jiraServer: ${{ vars.JIRA_SERVER }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
          gitHubPAT: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          roleToAssumeForEcr: ${{ vars.AWS_ROLE_TO_ASSUME_FOR_ECR }}
          roleToAssumeForCluster: ${{ vars.AWS_ROLE_TO_ASSUME }}
          clusterName: ${{ vars.CLUSTER_NAME || '' }}
